/**
 * Fee Receipt List Component
 * 
 * List of fee receipts with loading, empty, and error states
 * Uses FeeReceiptItem for individual receipts
 */

'use client';

import { Alert, AlertDescription } from '@/components/ui/alert';
import { Skeleton } from '@/components/ui/skeleton';
import { Button } from '@/components/ui/button';
import { ItemGroup, ItemSeparator } from '@/components/ui/item';
import {
    Receipt,
    AlertCircle,
    RefreshCw,
} from 'lucide-react';
import { FeeReceiptItem } from './fee-receipt-item';
import type { FeeReceipt } from '@/lib/branch-system/types/fee-receipts.types';

interface FeeReceiptListProps {
    receipts: FeeReceipt[];
    onViewDetails: (receipt: FeeReceipt) => void;
    isLoading?: boolean;
    error?: string | null;
    onRefresh?: () => void;
}

/**
 * Loading skeleton for receipt list
 */
function ReceiptListSkeleton() {
    return (
        <div className="space-y-2">
            {[...Array(5)].map((_, i) => (
                <div key={i} className="flex items-center gap-4 px-4 py-3 rounded-xl border">
                    <Skeleton className="w-10 h-10 rounded-xl" />
                    <div className="flex-1 space-y-2">
                        <Skeleton className="h-4 w-32" />
                        <Skeleton className="h-3 w-48" />
                    </div>
                    <div className="flex flex-col items-end gap-1">
                        <Skeleton className="h-4 w-20" />
                        <Skeleton className="h-3 w-16" />
                    </div>
                </div>
            ))}
        </div>
    );
}

/**
 * Empty state component
 */
function EmptyState() {
    return (
        <div className="flex flex-col items-center justify-center py-16">
            <div className="rounded-full bg-muted p-6 mb-4">
                <Receipt className="h-12 w-12 text-muted-foreground" />
            </div>
            <h3 className="text-lg font-semibold mb-2">No Fee Receipts</h3>
            <p className="text-sm text-muted-foreground max-w-md text-center">
                You don&apos;t have any fee receipts yet. Receipts will appear here
                once they are generated by your coaching center.
            </p>
        </div>
    );
}

/**
 * Error state component
 */
function ErrorState({
    error,
    onRetry,
}: {
    error: string;
    onRetry?: () => void;
}) {
    return (
        <div className="flex flex-col items-center justify-center py-12">
            <Alert variant="destructive" className="max-w-md mb-4">
                <AlertCircle className="h-4 w-4" />
                <AlertDescription>{error}</AlertDescription>
            </Alert>
            {onRetry && (
                <Button variant="outline" onClick={onRetry} className="gap-2">
                    <RefreshCw className="h-4 w-4" />
                    Try Again
                </Button>
            )}
        </div>
    );
}

export function FeeReceiptList({
    receipts,
    onViewDetails,
    isLoading = false,
    error,
    onRefresh,
}: FeeReceiptListProps) {
    // Loading state
    if (isLoading) {
        return <ReceiptListSkeleton />;
    }

    // Error state
    if (error) {
        return <ErrorState error={error} onRetry={onRefresh} />;
    }

    // Empty state
    if (receipts.length === 0) {
        return <EmptyState />;
    }

    return (
        <ItemGroup className="divide-y divide-border rounded-xl border bg-card overflow-hidden">
            {receipts.map((receipt, index) => (
                <div key={receipt.id}>
                    <FeeReceiptItem
                        receipt={receipt}
                        onViewDetails={onViewDetails}
                    />
                    {index < receipts.length - 1 && <ItemSeparator />}
                </div>
            ))}
        </ItemGroup>
    );
}
